apiVersion: batch/v1
kind: Job
metadata:
  name: alerting-db-ctrl-job
  namespace: kubesphere-alerting-system
  labels:
    app: alerting
    job: alerting-db-ctrl
    version: v0.1.0
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: alerting
        job: alerting-db-ctrl
        version: v0.1.0
      name: alerting-db-ctrl
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.openpitrix-system.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - command: ["flyway", "-X", "-url=jdbc:mysql://openpitrix-db.openpitrix-system.svc/alert", "-user=root", "-validateOnMigrate=false", "-locations=filesystem:/flyway/sql/alert", "migrate"]
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        image: dockerhub.qingcloud.com/ksalerting/dbinit
        imagePullPolicy: Always
        name: alerting-db-ctrl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
