apiVersion: v1
kind: Service
metadata:
  name: alerting-client-server
  namespace: kubesphere-alerting-system
spec:
  selector:
    app: alerting-client
  ports:
  - name: alerting-client-http
    protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alerting-client
  name: alerting-client
  namespace: kubesphere-alerting-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-client
  template:
    metadata:
      labels:
        app: alerting-client
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.openpitrix-system.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-redis
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z redis.kubesphere-system.svc 6379; do echo "waiting for redis"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.openpitrix-system.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - command:
        - /alerting/alert
        image: dockerhub.qingcloud.com/ksalerting/alerting
        imagePullPolicy: Always
        name: alerting-client
        env:
        - name: ALERT_APP_RUN_MODE
          value: "client"
        - name: ALERT_MYSQL_HOST
          value: "openpitrix-db.openpitrix-system.svc"
        - name: ALERT_ETCD_ENDPOINTS
          value: "openpitrix-etcd.openpitrix-system.svc:2379"
        - name: ALERT_APP_HOST
          value: "alerting-manager-server.kubesphere-alerting-system"
        - name: ALERT_APP_NOTIFICATION_HOST
          value: "notification.kubesphere-alerting-system.svc:9201"
        ports:
        - containerPort: 9200
          protocol: TCP
