apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alerting-executor
  name: alerting-executor
  namespace: kubesphere-alerting-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alerting-executor
  template:
    metadata:
      labels:
        app: alerting-executor
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.openpitrix-system.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-redis
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z redis.kubesphere-system.svc 6379; do echo "waiting for redis"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.openpitrix-system.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - command:
        - /alerting/adapter
        image: dockerhub.qingcloud.com/ksalerting/adapter
        imagePullPolicy: Always
        name: alerting-adapter
        env:
        - name: ADAPTER_APP_MONITORING_HOST
          value: "http://ks-apiserver.kubesphere-system.svc/kapis/monitoring.kubesphere.io/v1alpha2"
      - command:
        - /alerting/alert
        image: dockerhub.qingcloud.com/ksalerting/alerting
        imagePullPolicy: Always
        name: alerting-executor
        env:
        - name: ALERT_APP_RUN_MODE
          value: "executor"
        - name: ALERT_MYSQL_HOST
          value: "openpitrix-db.openpitrix-system.svc"
        - name: ALERT_ETCD_ENDPOINTS
          value: "openpitrix-etcd.openpitrix-system.svc:2379"
        - name: ALERT_QUEUE_TYPE
          value: redis
        - name: ALERT_QUEUE_ADDR
          value: redis://redis.kubesphere-system.svc:6379
        - name: ALERT_APP_NOTIFICATION_HOST
          value: "notification.kubesphere-alerting-system.svc:9201"
